version: "3"

services:
  frontend:
    image: ${HW_IMAGE_FRONTEND}
    depends_on:
      - "api"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - portfolio-website
    extra_hosts:
      - host.docker.internal:host-gateway
  api:
    image: ${HW_IMAGE_API}
    ports:
      - "8080:3000"
    networks:
      - portfolio-website

networks:
  portfolio-website: {}
