name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Write SSL key file
        env:
          AUTH: ${{ secrets.NGINX_SSL_PRIVATE_KEY }}
        run: |
          echo "$NGINX_SSL_PRIVATE_KEY" | base64 --decode > ${HOME}/nginx/ssl/hoppingmode.com.key
          echo "$NGINX_SSL_CERT" | base64 --decode > ${HOME}/nginx/ssl/hoppingmode.com.crt
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      - name: Clean up
        run: |
          rm ${HOME}/nginx/ssl/hoppingmode.com.key
          rm ${HOME}/nginx/ssl/hoppingmode.com.crt
